In [38]:
def CreateFolder(directory):
    try:
        if not os.path.exists(directory):
            os.makedirs(directory)
            print(f'{directory}_loction:',glob.glob(os.getcwd()+f'\\{directory}'))
        else:
            print('already')
    except OSError:
        print('Error:Creating directory.'+directory)

In [8]:
from PIL import Image, ImageOps
import os,sys,glob,time

In [2]:
glob.glob(os.getcwd())

['C:\\Food_detecting\\PERPRO']

In [11]:
raw_path =r'Z:\testCut' 
class_path = os.getcwd()

In [10]:
food_list = [i.split('\\')[-1] for i in glob.glob(raw_path+'/*')]
dir_name = [eng for kor, eng in dir_food.items() if kor in food_list]

['갈비구이',
 '계란찜',
 '김치찌개',
 '미역줄기볶음',
 '백김치',
 '불고기',
 '삼계탕',
 '순두부찌개',
 '애호박볶음',
 '후라이드치킨']

In [1]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.callbacks import ModelCheckpoint
from keras.layers.normalization import BatchNormalization
import numpy as np

Using TensorFlow backend.


In [ ]:
# classifier = Sequential()

# classifier.add(Conv2D(16, (3, 3), padding='same', activation='relu', input_shape=(224, 224, 3)))
# classifier.add(Conv2D(16, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
# classifier.add(Conv2D(64, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Conv2D(32, (3, 3), padding='same', activation='relu'))
# classifier.add(Conv2D(32, (3, 3), activation='relu'))
# classifier.add(MaxPooling2D(pool_size=(2, 2)))
# classifier.add(Dropout(0.25))

# classifier.add(Flatten())
# classifier.add(Dense(512, activation='relu'))
# classifier.add(Dropout(0.5))
# classifier.add(Dense(10, activation='softmax'))

In [2]:
model = Sequential()

model.add(Conv2D(16, (3, 3), padding='same', use_bias=False, input_shape=(224, 224, 3)))
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
model.add(Dropout(0.2))

model.add(Conv2D(32, (3, 3), padding='same', use_bias=False))
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
model.add(Dropout(0.2))

model.add(Conv2D(64, (3, 3), padding='same', use_bias=False))
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(4, 4), strides=(4, 4), padding='same'))
model.add(Dropout(0.2))

model.add(Conv2D(128, (3, 3), padding='same', use_bias=False))
model.add(BatchNormalization(axis=3, scale=False))
model.add(Activation("relu"))
model.add(Flatten())
model.add(Dropout(0.2))

model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 224, 224, 16)      432       
_________________________________________________________________
batch_normalization_1 (Batch (None, 224, 224, 16)      48        
_________________________________________________________________
activation_1 (Activation)    (None, 224, 224, 16)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 16)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 56, 56, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 56, 56, 32)        4608      
______________________________________

In [3]:
from keras.preprocessing.image import ImageDataGenerator

In [4]:
# train_datagen = ImageDataGenerator(rescale = 1./255)

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255,
                                   rotation_range=10,
                                   width_shift_range=0.2,
                                   height_shift_range=0.2,
                                   shear_range=0.7,
                                   zoom_range=[0.9, 2.2],
                                   horizontal_flip=True,
                                   vertical_flip=True,
                                   fill_mode='nearest',
                                   validation_split=0.33)

In [9]:
os.getcwd()

'C:\\Food_detecting\\PERPRO'

In [5]:
PATH='C:\Food_detecting\data'

In [6]:
training_set = train_datagen.flow_from_directory(PATH,
                                                 shuffle=True,
                                                 seed=13,
                                                 target_size = (224, 224),
                                                 batch_size = 15,
                                                 class_mode = 'categorical',
                                                 subset="training")
validation_set = train_datagen.flow_from_directory(PATH,
                                                 shuffle=True,
                                                 seed=13,
                                                 target_size = (224, 224),
                                                 batch_size = 10,
                                                 class_mode = 'categorical',
                                                 subset="validation")

Found 6462 images belonging to 10 classes.
Found 3176 images belonging to 10 classes.


In [7]:
from keras.callbacks import CSVLogger

csv_logger = CSVLogger('./log.csv', append=True, separator=';')

hist = model.fit_generator(training_set,
                         steps_per_epoch = 20,
                         epochs = 1000,
                         validation_data = validation_set,
                         validation_steps = 10,
                         callbacks=[csv_logger])


Epoch 1/1000
20/20 [==============================] - 12s 614ms/step - loss: 2.6694 - accuracy: 0.1733 - val_loss: 2.2333 - val_accuracy: 0.1200
Epoch 2/1000
20/20 [==============================] - 11s 551ms/step - loss: 2.0368 - accuracy: 0.2967 - val_loss: 2.5285 - val_accuracy: 0.0400
Epoch 3/1000
20/20 [==============================] - 11s 545ms/step - loss: 1.7287 - accuracy: 0.3633 - val_loss: 2.8461 - val_accuracy: 0.1100
Epoch 4/1000
20/20 [==============================] - 11s 537ms/step - loss: 1.7379 - accuracy: 0.3569 - val_loss: 4.1310 - val_accuracy: 0.0800
Epoch 5/1000
20/20 [==============================] - 11s 544ms/step - loss: 1.6412 - accuracy: 0.4067 - val_loss: 3.3492 - val_accuracy: 0.1300
Epoch 6/1000
20/20 [==============================] - 11s 547ms/step - loss: 1.6222 - accuracy: 0.3833 - val_loss: 3.9849 - val_accuracy: 0.1100
Epoch 7/1000
20/20 [==============================] - 11s 547ms/step - loss: 1.4621 - accuracy: 0.4667 - val_loss: 5.2030 - val_a

Epoch 56/1000
20/20 [==============================] - 11s 538ms/step - loss: 1.1471 - accuracy: 0.5567 - val_loss: 2.1373 - val_accuracy: 0.4100
Epoch 57/1000
20/20 [==============================] - 11s 537ms/step - loss: 1.1864 - accuracy: 0.5533 - val_loss: 2.0256 - val_accuracy: 0.3900
Epoch 58/1000
20/20 [==============================] - 11s 538ms/step - loss: 1.1314 - accuracy: 0.5300 - val_loss: 1.7749 - val_accuracy: 0.5100
Epoch 59/1000
20/20 [==============================] - 11s 536ms/step - loss: 1.1401 - accuracy: 0.5825 - val_loss: 2.1298 - val_accuracy: 0.4900
Epoch 60/1000
20/20 [==============================] - 11s 535ms/step - loss: 1.2599 - accuracy: 0.5200 - val_loss: 1.2986 - val_accuracy: 0.4700
Epoch 61/1000
20/20 [==============================] - 11s 539ms/step - loss: 1.4273 - accuracy: 0.4367 - val_loss: 1.9517 - val_accuracy: 0.3800
Epoch 62/1000
20/20 [==============================] - 11s 537ms/step - loss: 1.2157 - accuracy: 0.5233 - val_loss: 1.3639 -

20/20 [==============================] - 11s 536ms/step - loss: 1.1522 - accuracy: 0.5567 - val_loss: 1.1082 - val_accuracy: 0.6000
Epoch 113/1000
20/20 [==============================] - 11s 535ms/step - loss: 0.9432 - accuracy: 0.6533 - val_loss: 1.4911 - val_accuracy: 0.5100
Epoch 114/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.9876 - accuracy: 0.6267 - val_loss: 1.9101 - val_accuracy: 0.4900
Epoch 115/1000
20/20 [==============================] - 11s 536ms/step - loss: 1.0575 - accuracy: 0.5867 - val_loss: 1.8914 - val_accuracy: 0.2400
Epoch 116/1000
20/20 [==============================] - 11s 560ms/step - loss: 1.1011 - accuracy: 0.5433 - val_loss: 0.9173 - val_accuracy: 0.4400
Epoch 117/1000
20/20 [==============================] - 11s 553ms/step - loss: 1.1157 - accuracy: 0.5286 - val_loss: 1.6411 - val_accuracy: 0.5000
Epoch 118/1000
20/20 [==============================] - 11s 546ms/step - loss: 1.0141 - accuracy: 0.6100 - val_loss: 2.2834 - val_acc

Epoch 168/1000
20/20 [==============================] - 11s 542ms/step - loss: 1.0190 - accuracy: 0.5900 - val_loss: 2.5763 - val_accuracy: 0.5000
Epoch 169/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.9201 - accuracy: 0.6433 - val_loss: 0.9700 - val_accuracy: 0.5100
Epoch 170/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.9516 - accuracy: 0.6400 - val_loss: 1.2866 - val_accuracy: 0.5800
Epoch 171/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.9086 - accuracy: 0.6433 - val_loss: 2.2028 - val_accuracy: 0.4600
Epoch 172/1000
20/20 [==============================] - 11s 546ms/step - loss: 0.9630 - accuracy: 0.6200 - val_loss: 0.5460 - val_accuracy: 0.6700
Epoch 173/1000
20/20 [==============================] - 11s 545ms/step - loss: 0.8632 - accuracy: 0.6768 - val_loss: 0.4771 - val_accuracy: 0.5900
Epoch 174/1000
20/20 [==============================] - 11s 550ms/step - loss: 1.0730 - accuracy: 0.5900 - val_loss: 1

Epoch 224/1000
20/20 [==============================] - 11s 544ms/step - loss: 0.9062 - accuracy: 0.6467 - val_loss: 0.8323 - val_accuracy: 0.5300
Epoch 225/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.8207 - accuracy: 0.6667 - val_loss: 0.9181 - val_accuracy: 0.6600
Epoch 226/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.9222 - accuracy: 0.6433 - val_loss: 1.2957 - val_accuracy: 0.5900
Epoch 227/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.9474 - accuracy: 0.6233 - val_loss: 0.9651 - val_accuracy: 0.4400
Epoch 228/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.9778 - accuracy: 0.6333 - val_loss: 1.0070 - val_accuracy: 0.5700
Epoch 229/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.9497 - accuracy: 0.6200 - val_loss: 0.7401 - val_accuracy: 0.4600
Epoch 230/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.9265 - accuracy: 0.6267 - val_loss: 1

Epoch 280/1000
20/20 [==============================] - 11s 557ms/step - loss: 0.9294 - accuracy: 0.6367 - val_loss: 0.6746 - val_accuracy: 0.4600
Epoch 281/1000
20/20 [==============================] - 11s 569ms/step - loss: 0.7470 - accuracy: 0.7200 - val_loss: 0.6498 - val_accuracy: 0.6000
Epoch 282/1000
20/20 [==============================] - 12s 593ms/step - loss: 0.8032 - accuracy: 0.6767 - val_loss: 1.3703 - val_accuracy: 0.5900
Epoch 283/1000
20/20 [==============================] - 12s 576ms/step - loss: 0.8425 - accuracy: 0.6700 - val_loss: 1.3652 - val_accuracy: 0.5500
Epoch 284/1000
20/20 [==============================] - 11s 560ms/step - loss: 0.8821 - accuracy: 0.6567 - val_loss: 1.3040 - val_accuracy: 0.5500
Epoch 285/1000
20/20 [==============================] - 11s 570ms/step - loss: 0.8239 - accuracy: 0.6733 - val_loss: 2.2475 - val_accuracy: 0.4700
Epoch 286/1000
20/20 [==============================] - 12s 581ms/step - loss: 0.8422 - accuracy: 0.7100 - val_loss: 1

Epoch 336/1000
20/20 [==============================] - 11s 563ms/step - loss: 0.8643 - accuracy: 0.6600 - val_loss: 0.6306 - val_accuracy: 0.6600
Epoch 337/1000
20/20 [==============================] - 12s 598ms/step - loss: 0.9351 - accuracy: 0.6333 - val_loss: 1.1830 - val_accuracy: 0.5500
Epoch 338/1000
20/20 [==============================] - 12s 584ms/step - loss: 0.8547 - accuracy: 0.6733 - val_loss: 0.7281 - val_accuracy: 0.7000
Epoch 339/1000
20/20 [==============================] - 12s 590ms/step - loss: 0.8132 - accuracy: 0.6833 - val_loss: 1.4053 - val_accuracy: 0.5000
Epoch 340/1000
20/20 [==============================] - 12s 592ms/step - loss: 0.8140 - accuracy: 0.7067 - val_loss: 0.9353 - val_accuracy: 0.5800
Epoch 341/1000
20/20 [==============================] - 11s 565ms/step - loss: 0.7811 - accuracy: 0.6933 - val_loss: 1.4429 - val_accuracy: 0.5400
Epoch 342/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.8198 - accuracy: 0.6667 - val_loss: 2

Epoch 392/1000
20/20 [==============================] - 11s 548ms/step - loss: 0.7975 - accuracy: 0.7033 - val_loss: 1.3203 - val_accuracy: 0.5800
Epoch 393/1000
20/20 [==============================] - 11s 547ms/step - loss: 0.7626 - accuracy: 0.7200 - val_loss: 1.5469 - val_accuracy: 0.5300
Epoch 394/1000
20/20 [==============================] - 11s 544ms/step - loss: 0.8197 - accuracy: 0.6833 - val_loss: 0.6069 - val_accuracy: 0.6400
Epoch 395/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.8436 - accuracy: 0.6967 - val_loss: 2.5228 - val_accuracy: 0.5900
Epoch 396/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.6671 - accuracy: 0.7500 - val_loss: 1.1220 - val_accuracy: 0.6700
Epoch 397/1000
20/20 [==============================] - 11s 536ms/step - loss: 0.7723 - accuracy: 0.7133 - val_loss: 1.2025 - val_accuracy: 0.6000
Epoch 398/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.7649 - accuracy: 0.6967 - val_loss: 1

Epoch 448/1000
20/20 [==============================] - 11s 561ms/step - loss: 0.7972 - accuracy: 0.7133 - val_loss: 0.9632 - val_accuracy: 0.7700
Epoch 449/1000
20/20 [==============================] - 11s 555ms/step - loss: 0.8084 - accuracy: 0.6967 - val_loss: 1.6636 - val_accuracy: 0.5800
Epoch 450/1000
20/20 [==============================] - 11s 554ms/step - loss: 0.7333 - accuracy: 0.6833 - val_loss: 1.3621 - val_accuracy: 0.5500
Epoch 451/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.7863 - accuracy: 0.6967 - val_loss: 0.8561 - val_accuracy: 0.5900
Epoch 452/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.6913 - accuracy: 0.7033 - val_loss: 1.0250 - val_accuracy: 0.5000
Epoch 453/1000
20/20 [==============================] - 11s 545ms/step - loss: 0.6770 - accuracy: 0.7333 - val_loss: 0.5999 - val_accuracy: 0.6100
Epoch 454/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.7350 - accuracy: 0.7067 - val_loss: 2

Epoch 504/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6593 - accuracy: 0.7500 - val_loss: 0.5148 - val_accuracy: 0.6800
Epoch 505/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.8503 - accuracy: 0.6633 - val_loss: 1.0306 - val_accuracy: 0.6000
Epoch 506/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.7769 - accuracy: 0.7441 - val_loss: 2.5417 - val_accuracy: 0.6100
Epoch 507/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6798 - accuracy: 0.7133 - val_loss: 1.5175 - val_accuracy: 0.5000
Epoch 508/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.8134 - accuracy: 0.7033 - val_loss: 2.3481 - val_accuracy: 0.4700
Epoch 509/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.8043 - accuracy: 0.6900 - val_loss: 2.8100 - val_accuracy: 0.3958
Epoch 510/1000
20/20 [==============================] - 11s 547ms/step - loss: 0.6740 - accuracy: 0.7433 - val_loss: 1

Epoch 560/1000
20/20 [==============================] - 11s 544ms/step - loss: 0.7211 - accuracy: 0.7200 - val_loss: 1.4465 - val_accuracy: 0.6400
Epoch 561/1000
20/20 [==============================] - 11s 554ms/step - loss: 0.6888 - accuracy: 0.7467 - val_loss: 1.1264 - val_accuracy: 0.5500
Epoch 562/1000
20/20 [==============================] - 11s 535ms/step - loss: 0.6883 - accuracy: 0.7239 - val_loss: 1.3575 - val_accuracy: 0.5800
Epoch 563/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6736 - accuracy: 0.7300 - val_loss: 1.5112 - val_accuracy: 0.6100
Epoch 564/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.6236 - accuracy: 0.7800 - val_loss: 0.7414 - val_accuracy: 0.6300
Epoch 565/1000
20/20 [==============================] - 11s 546ms/step - loss: 0.6508 - accuracy: 0.7567 - val_loss: 0.6242 - val_accuracy: 0.5500
Epoch 566/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.7412 - accuracy: 0.7067 - val_loss: 1

Epoch 616/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6554 - accuracy: 0.7700 - val_loss: 1.3959 - val_accuracy: 0.5800
Epoch 617/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.7297 - accuracy: 0.7267 - val_loss: 1.4219 - val_accuracy: 0.6200
Epoch 618/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.7193 - accuracy: 0.7333 - val_loss: 1.3311 - val_accuracy: 0.6600
Epoch 619/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.6702 - accuracy: 0.7567 - val_loss: 1.3716 - val_accuracy: 0.6500
Epoch 620/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6817 - accuracy: 0.7533 - val_loss: 1.9591 - val_accuracy: 0.6700
Epoch 621/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6165 - accuracy: 0.7500 - val_loss: 0.4976 - val_accuracy: 0.7000
Epoch 622/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.5802 - accuracy: 0.7900 - val_loss: 1

Epoch 672/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.7535 - accuracy: 0.7100 - val_loss: 0.7213 - val_accuracy: 0.7400
Epoch 673/1000
20/20 [==============================] - 11s 538ms/step - loss: 0.7195 - accuracy: 0.7003 - val_loss: 0.2167 - val_accuracy: 0.6100
Epoch 674/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.7415 - accuracy: 0.7233 - val_loss: 0.4817 - val_accuracy: 0.7200
Epoch 675/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.7713 - accuracy: 0.7067 - val_loss: 1.1179 - val_accuracy: 0.5700
Epoch 676/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.7368 - accuracy: 0.7333 - val_loss: 1.2603 - val_accuracy: 0.6100
Epoch 677/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6140 - accuracy: 0.7833 - val_loss: 1.8506 - val_accuracy: 0.6400
Epoch 678/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6154 - accuracy: 0.7600 - val_loss: 0

Epoch 728/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6855 - accuracy: 0.7500 - val_loss: 1.4608 - val_accuracy: 0.6500
Epoch 729/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.5694 - accuracy: 0.7600 - val_loss: 0.4254 - val_accuracy: 0.7100
Epoch 730/1000
20/20 [==============================] - 11s 536ms/step - loss: 0.7622 - accuracy: 0.6936 - val_loss: 0.3226 - val_accuracy: 0.7300
Epoch 731/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.6767 - accuracy: 0.7567 - val_loss: 0.3459 - val_accuracy: 0.7100
Epoch 732/1000
20/20 [==============================] - 11s 538ms/step - loss: 0.6808 - accuracy: 0.7367 - val_loss: 0.6509 - val_accuracy: 0.5521
Epoch 733/1000
20/20 [==============================] - 11s 553ms/step - loss: 0.7770 - accuracy: 0.6733 - val_loss: 0.5474 - val_accuracy: 0.5100
Epoch 734/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.6641 - accuracy: 0.7333 - val_loss: 1

Epoch 784/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6668 - accuracy: 0.7433 - val_loss: 1.1821 - val_accuracy: 0.6100
Epoch 785/1000
20/20 [==============================] - 11s 544ms/step - loss: 0.7555 - accuracy: 0.7133 - val_loss: 1.3686 - val_accuracy: 0.6600
Epoch 786/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.6952 - accuracy: 0.7367 - val_loss: 1.4609 - val_accuracy: 0.6000
Epoch 787/1000
20/20 [==============================] - 11s 543ms/step - loss: 0.6635 - accuracy: 0.7267 - val_loss: 0.3229 - val_accuracy: 0.6800
Epoch 788/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6769 - accuracy: 0.7333 - val_loss: 0.7884 - val_accuracy: 0.6500
Epoch 789/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.5846 - accuracy: 0.7767 - val_loss: 1.3534 - val_accuracy: 0.6400
Epoch 790/1000
20/20 [==============================] - 11s 546ms/step - loss: 0.6434 - accuracy: 0.7700 - val_loss: 1

Epoch 840/1000
20/20 [==============================] - 11s 538ms/step - loss: 0.6680 - accuracy: 0.7306 - val_loss: 0.2578 - val_accuracy: 0.6000
Epoch 841/1000
20/20 [==============================] - 11s 552ms/step - loss: 0.6668 - accuracy: 0.7300 - val_loss: 0.7624 - val_accuracy: 0.5300
Epoch 842/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6911 - accuracy: 0.7100 - val_loss: 2.5790 - val_accuracy: 0.4700
Epoch 843/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6114 - accuracy: 0.7700 - val_loss: 3.7933 - val_accuracy: 0.5100
Epoch 844/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6265 - accuracy: 0.7533 - val_loss: 1.0321 - val_accuracy: 0.6000
Epoch 845/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.6418 - accuracy: 0.7700 - val_loss: 1.5596 - val_accuracy: 0.6800
Epoch 846/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6373 - accuracy: 0.7733 - val_loss: 1

Epoch 896/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.5548 - accuracy: 0.7900 - val_loss: 1.7741 - val_accuracy: 0.5400
Epoch 897/1000
20/20 [==============================] - 11s 539ms/step - loss: 0.6988 - accuracy: 0.7433 - val_loss: 0.7229 - val_accuracy: 0.5600
Epoch 898/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6287 - accuracy: 0.7567 - val_loss: 0.6724 - val_accuracy: 0.5600
Epoch 899/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6414 - accuracy: 0.7600 - val_loss: 4.3848 - val_accuracy: 0.3500
Epoch 900/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.5621 - accuracy: 0.7600 - val_loss: 0.9205 - val_accuracy: 0.5400
Epoch 901/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6095 - accuracy: 0.7733 - val_loss: 0.3252 - val_accuracy: 0.7100
Epoch 902/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.6251 - accuracy: 0.7500 - val_loss: 0

Epoch 952/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.6303 - accuracy: 0.7767 - val_loss: 0.8427 - val_accuracy: 0.6800
Epoch 953/1000
20/20 [==============================] - 11s 567ms/step - loss: 0.6194 - accuracy: 0.7833 - val_loss: 1.2955 - val_accuracy: 0.4100
Epoch 954/1000
20/20 [==============================] - 11s 529ms/step - loss: 0.5791 - accuracy: 0.7879 - val_loss: 0.7431 - val_accuracy: 0.6458
Epoch 955/1000
20/20 [==============================] - 11s 547ms/step - loss: 0.5987 - accuracy: 0.7500 - val_loss: 0.4430 - val_accuracy: 0.6600
Epoch 956/1000
20/20 [==============================] - 11s 542ms/step - loss: 0.5975 - accuracy: 0.7833 - val_loss: 0.4168 - val_accuracy: 0.6800
Epoch 957/1000
20/20 [==============================] - 11s 540ms/step - loss: 0.6643 - accuracy: 0.7367 - val_loss: 1.1170 - val_accuracy: 0.5800
Epoch 958/1000
20/20 [==============================] - 11s 541ms/step - loss: 0.7924 - accuracy: 0.7033 - val_loss: 0

In [8]:
from keras.models import load_model

model.save('food_keras_model.h5')

In [10]:
# 모델 평가하기
print("-- 모델 평가하기 --")

scores = model.evaluate_generator(
            validation_set,
            steps = 10)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

# 모델 예측하기
print("-- 모델 예측하기 --")

output = model.predict_generator(
            validation_set,
            steps = 10)
print(validation_set.class_indices)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)
print(validation_set.filenames)

-- 모델 평가하기 --
accuracy: 69.00%
-- 모델 예측하기 --
{'aehobakbokkeum': 0, 'baekkimchi': 1, 'bulgogi': 2, 'friedchicken': 3, 'galbigui': 4, 'gyeranjjim': 5, 'kimchijjigae': 6, 'miyeokjulgibokkeum': 7, 'samgyetang': 8, 'sundubujjigae': 9}
[[0.006 0.009 0.039 0.000 0.051 0.483 0.002 0.026 0.339 0.045]
 [0.002 0.004 0.000 0.000 0.000 0.869 0.004 0.000 0.116 0.005]
 [0.000 0.000 0.011 0.000 0.023 0.000 0.824 0.000 0.000 0.142]
 [0.899 0.046 0.001 0.000 0.000 0.005 0.001 0.002 0.016 0.030]
 [0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.994 0.005 0.000]
 [0.000 0.009 0.000 0.021 0.000 0.004 0.666 0.000 0.002 0.298]
 [0.000 0.003 0.011 0.000 0.001 0.007 0.488 0.000 0.001 0.488]
 [0.000 0.003 0.002 0.000 0.003 0.030 0.000 0.000 0.945 0.018]
 [0.000 0.013 0.000 0.211 0.000 0.003 0.691 0.000 0.002 0.081]
 [0.000 0.000 0.156 0.002 0.778 0.000 0.000 0.003 0.056 0.003]
 [0.000 0.000 0.000 0.967 0.000 0.033 0.000 0.000 0.000 0.000]
 [0.001 0.028 0.000 0.000 0.000 0.970 0.000 0.000 0.001 0.000]
 [0.000 0.000 

In [9]:
# output = classifier.predict_generator(test_set, steps=5)
# print(output)

NameError: name 'classifier' is not defined